services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: social-appliance:latest
    pull_policy: never
    env_file:
      - .env
    environment:
      - PORT=8000
      - NODE_ENV=production
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8000/api/health || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 10
      start_period: 20s
    networks:
      - webnet
    restart: unless-stopped

  caddy:
    image: caddy:2
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddydata:/data
      - caddyconfig:/config
    networks:
      - webnet
    restart: unless-stopped

volumes:
  caddydata:
  caddyconfig:

networks:
  webnet:
